name: Build and Publish Wheels

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64
            cibw_platform: linux
            cibw_arch: x86_64
          - os: ubuntu-latest
            target: aarch64
            cibw_platform: linux
            cibw_arch: aarch64
          - os: windows-latest
            target: x86_64
            cibw_platform: windows
            cibw_arch: x86_64
          - os: macos-latest
            target: arm64
            cibw_platform: macos
            cibw_arch: arm64

    steps:
      - uses: actions/checkout@v4
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist
      - uses: actions/upload-artifact@v6
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.target }}
          path: dist/*.whl

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          path: dist
      # - uses: actions/download-artifact@v7
      #   with:
      #     name: wheels-windows-latest
      #     path: dist
      # - uses: actions/download-artifact@v7
      #   with:
      #     name: wheels-macos-latest
      #     path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}